FROM node:18-slim

RUN apt-get update \
  && apt-get install -y --no-install-recommends openjdk-17-jre-headless curl \
  && rm -rf /var/lib/apt/lists/*

RUN npm install -g firebase-tools

WORKDIR /workspace/firebase

